# Site settings
title: Wired_programers 
description: "Where building softwares is not just a routine..."
baseurl: ""
url: "" # the name of your domain
logo_path: "../images/logo1.png"

# Hero
hero:
    hero_img: ../images/hero.jpg
    hero_title: Wired_programmers
    hero_description: Where building softwares is not just a routine...

# Contact form
api_token: # Enter API token here

# Contact info
contact:
    phone: 932 50 540
    emergency: 931 53 234
    email: info@wired_progs.com
    address: address

# Map
map:
    zoom: 17
    address: Gujarat india
    address_details: svg/min/logo.svg

# Social settings
facebook: http://facebook.com
twitter: http://twitter.com
instagram: http://instagram.com
youtube: http://youtube.com
skype: skype:obaez_design?userinfo
feed: yes

# Footer
copyright: © 2015 Extreme-Airs

# Build settings
markdown: kramdown

exclude: [
    package.json,
    Gruntfile.js,
    node_modules,
    .sass-cache,
    Gemfile,
    Gemfile.lock,
    .gitignore
]

# Theme Settings
analytics:
google_verification:
